"""
Django settings for r00 project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Play settings
GRID = {
    'x': 10,
    'y': 10,
}
BEGIN = {
    'x': 0,
    'y': 0,
}
MOVIES = {
    0: 'Fight_Club',
    1: 'The_Exorcist_(film)',
    2: 'Pulp_Fiction',
    3: 'A_Clockwork_Orange_(film)',
    4: 'Reservoir_Dogs',
    5: 'Scarface_(1983_film)',
    6: 'Snatch_(film)',
    7: 'Trainspotting_(film)',
    8: 'Shaun_of_the_Dead',
    9: 'French_Fried_Vacation',
    10: '300_(film)',
    11: 'Godzilla_(2014_film)'
}

FULL_MOVIE = {
    'Fight_Club'                : {'box_office': 100.9, 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2004, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'The_Exorcist_(film)'       : {'box_office': 12   , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2005, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Pulp_Fiction'              : {'box_office': 213.9, 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2006, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'A_Clockwork_Orange_(film)' : {'box_office': 26.6 , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2007, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Reservoir_Dogs'            : {'box_office': 2.8  , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2008, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Scarface_(1983_film)'      : {'box_office': 65.9 , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2009, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Snatch_(film)'             : {'box_office': 83.6 , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2010, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Trainspotting_(film)'      : {'box_office': 72   , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2011, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Shaun_of_the_Dead'         : {'box_office': 30   , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2012, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'French_Fried_Vacation'     : {'box_office': 17.3 , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2013, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    '300_(film)'                : {'box_office': 456  , 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2014, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'},
    'Godzilla_(2014_film)'      : {'box_office': 529.1, 'synopsis': 'movie synopsis', 'directed_by': 'the director', 'year': 2015, 'actors': ['Actor A', 'Actor B', 'Actor C'], 'poster': 'https://upload.wikimedia.org/wikipedia/en/1/10/Godzilla_%282014%29_poster.jpg'}
}

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '27o#g0!2!k%$8p)2a7&2q^2iyoygf-tq(v9oml5!&f24mnyc%e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'titleScreen',
    'worldMap',
    'battle',
    'movieDex',
    'options',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'r00.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'r00.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'templates', 'media'),
]
